version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-verda
    binary: terraform-provider-verda
    main: .
    ldflags:
      - -s -w -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      # Windows arm64 not supported by Terraform
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - zip
    name_template: >-
      terraform-provider-verda_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - none*

checksum:
  name_template: terraform-provider-verda_{{ .Version }}_SHA256SUMS
  extra_files:
    - glob: terraform-provider-verda_{{ .Version }}_manifest.json

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "{{ .Env.GPG_PASSPHRASE }}"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  extra_files:
    - glob: terraform-provider-verda_{{ .Version }}_manifest.json
